# Generated by Django 3.2.6 on 2021-10-07 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_query',
            name='dr_response',
            field=models.TextField(blank=True, default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer_query',
            name='dr_response_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
