# Generated by Django 3.2.6 on 2021-10-08 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0001_initial'),
        ('customerapp', '0002_auto_20211007_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('time', models.TimeField()),
                ('reason_for_appointment', models.TextField(max_length=200)),
                ('fee', models.IntegerField()),
                ('doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorapp.doctor_reg')),
            ],
        ),
    ]
