# Generated by Django 3.2.6 on 2021-10-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0003_book_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_appointment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='book_appointment',
            name='prescription',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
