# Generated by Django 3.2.6 on 2021-10-11 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0004_auto_20211011_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_appointment',
            name='file',
            field=models.FileField(blank=True, default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
