# Generated by Django 3.2.6 on 2021-10-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0005_alter_book_appointment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_appointment',
            name='file',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
    ]
