# Generated by Django 3.2.6 on 2021-10-12 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0006_alter_book_appointment_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_appointment',
            name='file',
        ),
    ]
