# Generated by Django 3.2.6 on 2021-10-12 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0007_remove_book_appointment_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_appointment',
            old_name='time',
            new_name='appointment_time',
        ),
    ]
