# Generated by Django 3.2.6 on 2021-10-19 05:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0008_rename_time_book_appointment_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_appointment',
            name='customer_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customerapp.customer_reg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_appointment',
            name='file',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
    ]
