# Generated by Django 3.2.6 on 2021-10-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0009_auto_20211019_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_appointment',
            name='status',
            field=models.CharField(default='waiting', max_length=50),
        ),
    ]
