# Generated by Django 3.2.6 on 2021-10-20 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0001_initial'),
        ('customerapp', '0010_book_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_appointment',
            name='customer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customerapp.customer_reg'),
        ),
        migrations.AlterField(
            model_name='book_appointment',
            name='doctor_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctorapp.doctor_reg'),
        ),
    ]
