# Generated by Django 3.2.6 on 2021-10-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0011_auto_20211020_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_appointment',
            name='appointment_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='book_appointment',
            name='appointment_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='book_appointment',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='book_appointment',
            name='prescription',
            field=models.TextField(max_length=200),
        ),
    ]
