# Generated by Django 3.2.6 on 2021-10-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0012_auto_20211020_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_appointment',
            name='fee',
            field=models.IntegerField(null=True),
        ),
    ]
