# Generated by Django 3.2.6 on 2021-10-20 05:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0001_initial'),
        ('customerapp', '0013_alter_book_appointment_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_appointment',
            name='appointment_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book_appointment',
            name='appointment_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book_appointment',
            name='customer_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customerapp.customer_reg'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book_appointment',
            name='doctor_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctorapp.doctor_reg'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book_appointment',
            name='fee',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
