# Generated by Django 3.2.6 on 2021-10-21 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0014_auto_20211020_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_pic',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerapp.customer_reg'),
        ),
    ]
