# Generated by Django 4.0.5 on 2022-07-28 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0015_alter_customer_pic_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_appointment',
            name='fee',
        ),
    ]
