# Generated by Django 3.2.6 on 2021-10-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('available_date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('qualification', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=50)),
                ('appointment_fee', models.IntegerField()),
                ('experience', models.CharField(max_length=50)),
                ('about_me', models.TextField()),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
